<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="yuzgdeMacBook-Pro.local" failures="1" tests="2" name="Default test" time="5.041" errors="0" timestamp="18 Dec 2020 03:20:22 GMT">
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldFail" time="1.015">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.yiibai4.TestTimeout.testThisShouldFail() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.yiibai4.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000
	at java.base@14.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testThisShouldFail -->
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldPass" time="4.006"/>
</testsuite> <!-- Default test -->
