<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yuzgdeMacBook-Pro.local" failures="0" tests="2" name="com.yiibai4.TestTimeout" time="5.020" errors="1" timestamp="17 Dec 2020 05:54:49 GMT" skipped="0">
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldPass" time="4.008"/>
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldFail" time="1.012">
    <error message="Method com.yiibai4.TestTimeout.testThisShouldFail() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.yiibai4.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000
	at java.base@14.0.2/java.lang.invoke.MethodType.hashCode(MethodType.java:846)
	at java.base@14.0.2/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base@14.0.2/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1317)
	at java.base@14.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:312)
	at java.base@14.0.2/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:377)
	at java.base@14.0.2/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
	at java.base@14.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- com.yiibai4.TestTimeout -->
