<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yuzgdeMacBook-Pro.local" failures="0" tests="2" name="com.yiibai4.TestTimeout" time="5.021" errors="1" timestamp="18 Dec 2020 03:20:22 GMT" skipped="0">
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldPass" time="4.006"/>
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldFail" time="1.015">
    <error message="Method com.yiibai4.TestTimeout.testThisShouldFail() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.yiibai4.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000
	at java.base@14.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- com.yiibai4.TestTimeout -->
